@host = http://localhost:5056
@idToken = eyJhbGciOiJSUzI1NiIsImtpZCI6ImVlYzIxN2Q0MThjYjhlNWEzMTQzMThhMGQyZmZhNGUwY2ViMmU0Y2MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZmxvcmluLXRpbWFyaXUtbGljZW50YSIsImF1ZCI6ImZsb3Jpbi10aW1hcml1LWxpY2VudGEiLCJhdXRoX3RpbWUiOjE3NzkxMDY1ODEsInVzZXJfaWQiOiJ2NGxsMmF6bkpoYWxHamtpbEVpYnAwSHFFN0MzIiwic3ViIjoidjRsbDJhem5KaGFsR2praWxFaWJwMEhxRTdDMyIsImlhdCI6MTc3OTEwNjU4MSwiZXhwIjoxNzc5MTEwMTgxLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidGVzdEBleGFtcGxlLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6ImN1c3RvbSJ9fQ.gjduUzZ2HmopyRmZ06u4SiYtqtBu84pVz2IDEdTQihykc_uracUfBEZWG7Yr7sEHWPLyD2uveXIxW5p0LNpz-Tldi_AQ7k085BvxP2qdGAF4hCaqcKwoU7LdaZyeusfl54I3xUGlg7Lj0AjoJ-k-CAavM2YOt9lg88x_KW9HCHoyN56Kz0PyOxcFo2_pl-x12iyBiJtrju_9NlWpy9PSkidtYQ-Rq6mqEbVIDRVD8sSXozdf5Ya4mbQufwrRsGLNnlcJU5sL17aeFrbkg0dViV95d0A_1dsHVEDwpdIfQY5eTfl5_aW8G5FyB4WeaiFBe8dy6EMa-xohfaSQlLJlJQ

### Test cu token valid
GET {{host}}/api/me
Authorization: Bearer {{idToken}}